* Dotfiles

A collection of configuration files managed with GNU Stow.

** Prerequisites

See =deps.txt= for required tools. [[https://www.gnu.org/software/stow/][GNU Stow]] is the only hard dependency.

*** Gnu Stow

GNU Stow is a symlink farm manager. See the [[https://www.gnu.org/software/stow/][official docs]] for details.

** Usage

A =.stowrc= file at the root configures stow defaults:

#+begin_src sh
  --target=~
  --dir=~/.dotfiles
  --no-folding
#+end_src

- =--target=~= - symlinks are created in =~=
- =--dir=~/.dotfiles= - package root is =~/.dotfiles=
- =--no-folding= - real directories are always created, never directory symlinks. Required because multiple packages contribute to shared directories like =~/.config/= and =~/.local/bin/=

Stow picks up =.stowrc= automatically when invoked from =~/.dotfiles=. To make it work from *any* directory, symlink it to =~=:

#+begin_src sh
  ln -s ~/.dotfiles/.stowrc ~/.stowrc
#+end_src

To stow a package:

#+begin_src sh
  stow emacs
#+end_src

To stow all packages at once:

#+begin_src sh
  cd ~/.dotfiles && stow */
#+end_src

Each package's directory structure is mirrored as symlinks in =~=.

** Homebrew

macOS packages are managed with [[https://brew.sh/][Homebrew]]. The Brewfile is tracked via =brew bundle=.

Dump currently installed packages to the Brewfile:

#+begin_src sh
  brew bundle dump --global --force
#+end_src

With =$XDG_CONFIG_HOME= set, the Brewfile is placed in =~/.config/homebrew/= and tracked by this repo.

To install all packages on a new system:

#+begin_src sh
  brew bundle --global
#+end_src

See the [[https://docs.brew.sh/Brew-Bundle-and-Brewfile][brew bundle docs]] for details.
