#!/usr/bin/env bash

# Linux
# -----
if [[ "$(uname)" != "Linux" ]]; then
    return
fi

if ! shopt -oq posix; then
    if [ -f /usr/share/bash-completion/bash_completion ]; then
        . /usr/share/bash-completion/bash_completion
    elif [ -f /etc/bash_completion ]; then
        . /etc/bash_completion
    fi
fi

alias hx=helix

# find git-prompt file to be used in main bash file
if [[ -e /usr/share/git/git-prompt.sh ]]; then
    . /usr/share/git/git-prompt.sh
fi
