#!/usr/bin/env bash

# Linux
# -----
if [[ "$(uname)" != "Linux" ]]; then
  return
fi

. /usr/share/git-core/contrib/completion/git-prompt.sh

GIT_PS1_SHOWCOLORHINTS=1
GIT_PS1_SHOWDIRTYSTATE=1
GIT_PS1_SHOWSTASHSTATE=1
GIT_PS1_SHOWUPSTREAM="auto"

export PROMPT_COMMAND='history -a'
export PS1='\[\e[1;32m\]\u@\h\[\e[0m\]:\[\e[1;34m\]\w\[\e[0m\]$(__git_ps1 " (%s)")\$ '
