#!/usr/bin/env bash

# macOS
# -----
if [[ "$(uname)" != "Darwin" ]]; then
  return
fi

if [ -z "$PS1" ]; then
  return
fi

# source git prompt script. Used in main bashrc file
. /opt/homebrew/etc/bash_completion.d/git-prompt.sh

[ -r "/etc/bashrc_$TERM_PROGRAM" ] && . "/etc/bashrc_$TERM_PROGRAM"

# change lang to en_US but keep encoding
export LANG=${LANG/sv_SE/en_US}

## Homebrew
## --------
export PATH="/opt/homebrew/bin:$PATH"

# GNU utilities without "g" prefix. Replaces ls, cat, etc.
export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"

# use gnu-awk instead of awk on mac
export PATH="/opt/homebrew/opt/gawk/libexec/gnubin:$PATH"

# go back to using BSD provided stty instead of GNU coreutils version
export PATH="$HOME/.local/bin:$PATH"

# Add bash completion for brew packages
[[ -r "/opt/homebrew/etc/profile.d/bash_completion.sh" ]] && . "/opt/homebrew/etc/profile.d/bash_completion.sh"

if type brew &>/dev/null
then
  HOMEBREW_PREFIX="$(brew --prefix)"
  if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]
  then
    source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
  else
    for COMPLETION in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*
    do
      [[ -r "${COMPLETION}" ]] && source "${COMPLETION}"
    done
  fi
fi

# dotnet from M$ website, already in path
DOTNET_ROOT="$(dirname "$(which dotnet)")"
export DOTNET_ROOT

# gnu coreutils version of stty doesn't work well with a lot of tools, so
# for now we make sure that the built-in BSD provided stty is used instead by
# creating a symbolic link into our .local/bin dir:
#
# mkdir -p ~/.local/bin
# cd ~/.local/bin
# ln -sf /bin/stty stty
