#!/usr/bin/env bash

# Exit early if not macos
if [[ "$OSTYPE" != "darwin"* ]]; then
  return
fi

if [ -z "$PS1" ]; then
  return
fi

# PS1='\h:\W \u\$ '

# Make bash check its window size after a process completes
shopt -s checkwinsize

[ -r "/etc/bashrc_$TERM_PROGRAM" ] && . "/etc/bashrc_$TERM_PROGRAM"

# change lang to en_US but keep encoding
export LANG=${LANG/sv_SE/en_US}

export PATH="/opt/homebrew/bin:$PATH"

# GNU utilities without "g" prefix. Replaces ls, cat, etc.
export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"

# use gnu-awk instead of awk on mac
export PATH="/opt/homebrew/opt/gawk/libexec/gnubin:$PATH"

# dotnet from M$ website, already in path
DOTNET_ROOT="$(dirname "$(which dotnet)")"
export DOTNET_ROOT

# Add python from pyenv to path
export PATH="$PATH:$HOME/.pyenv/shims"

[[ -r "/opt/homebrew/etc/profile.d/bash_completion.sh" ]] && . "/opt/homebrew/etc/profile.d/bash_completion.sh"

if type brew &>/dev/null
then
  HOMEBREW_PREFIX="$(brew --prefix)"
  if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]
  then
    source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
  else
    for COMPLETION in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*
    do
      [[ -r "${COMPLETION}" ]] && source "${COMPLETION}"
    done
  fi
fi

alias ls="ls --color"
alias grep="grep --color"

eval "$(starship init bash)"
