;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        complete-symbol
        evil-backward-word-begin
        evil-delete
        evil-next-visual-line
        evil-previous-visual-line
        evil-undo
        markdown-electric-backquote
        markdown-outdent-or-delete
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-self-insert-command
        org-yank
        surround-insert
        ultra-scroll
        ))

(setq mc/cmds-to-run-once
      '(
        hydra-multiple-cursors/mc/mark-next-like-this
        ))
