;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-backward-char
        evil-change
        evil-exit-visual-state
        evil-force-normal-state
        evil-forward-char
        evil-next-line
        evil-normal-state
        evil-previous-line
        hydra-multiple-cursors/mc/mark-next-like-this
        kill-region
        org-self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        ))
