#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0 # 0.5
yabai -m config window_animation_frame_rate  120
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.9
yabai -m config window_border                off
yabai -m config window_border_hidpi          on
yabai -m config window_border_blur           on
yabai -m config window_border_width          2 # even integer number
# yabai -m config window_border_radius         11
yabai -m config active_window_border_color   0xffc4a7e7
yabai -m config normal_window_border_color   0xff51425C
yabai -m config insert_feedback_color        0xff8E83B8
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

yabai -m rule --add label="sys" app="^System.*inställningar$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Vimac$" manage=off
yabai -m rule --add app="^Meddelanden$" manage=off
yabai -m rule --add app="^Messenger$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^RetroArch$" manage=off
yabai -m rule --add app="^JetBrains Toolbox$" manage=off
yabai -m rule --add app="^KeyboardCleanTool$" manage=off
yabai -m rule --add app="^Lunar$" manage=off
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^Påminnelser" manage=off
yabai -m rule --add app="^Steam$" manage=off
yabai -m rule --add app="^Ivory$" title="Ivory" manage=off
yabai -m rule --add app="^DevDocs$" manage=off
yabai -m rule --add title="\- Huddle$" manage=off

echo "yabai configuration loaded.."
